on:
  push:
    paths:
      - '**/*.ps1'

jobs:
  sign-script:
    runs-on: windows-latest
    name: Sign PS script with Trusted Signing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sign files with Trusted Signing
        uses: azure/trusted-signing-action@v0.4.0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://weu.codesigning.azure.net/
          trusted-signing-account-name: ${{ secrets.AZURE_SIGNING_ACCOUNT }}
          certificate-profile-name: ${{ secrets.AZURE_CERT_PROFILE }}
          files-folder: .\
          files-folder-filter: ps1
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
          
      - name: Upload signed script
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: signed-script
          path: '**/*.ps1'

